name: "Setup Node.js environment"
description: "Setup Node.js environment"
runs:
  using: "composite"
  steps:
      - uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
